name: GitHub Snake Game

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: AswaniVijoy
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Print SVG for debugging
        run: cat dist/github-contribution-grid-snake.svg

      - name: Push snake to output branch
        run: |
          sudo rm -rf dist/.git
          cd dist
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b output
          git add .
          git commit -m "Generate snake animation"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/AswaniVijoy/AswaniVijoy.git output
